# Generated by Django 4.2.23 on 2025-09-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="active",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="active",
        ),
    ]
