# Generated by Django 4.2.23 on 2025-09-02 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("KES", "Kenyan Shilling"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                        ],
                        db_index=True,
                        default="KES",
                        max_length=3,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[utils.validators.validate_e164_phone],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa (mobile money)"),
                            ("bank_transfer", "Bank Transfer"),
                        ],
                        db_index=True,
                        default="mpesa",
                        max_length=32,
                    ),
                ),
                (
                    "provider_ref",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=120,
                        null=True,
                        unique=True,
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status"], name="payments_pa_status_7ad4af_idx"
                    ),
                    models.Index(
                        fields=["currency"], name="payments_pa_currenc_b1f04b_idx"
                    ),
                    models.Index(
                        fields=["method"], name="payments_pa_method_70cfb8_idx"
                    ),
                ],
            },
        ),
    ]
