# Generated by Django 4.2.23 on 2025-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("seller", "seller"),
                    ("customer", "customer"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
    ]
